
on:
  pull_request:
    branches:
    - main

jobs:
  check:
   runs-on: ubuntu-latest
   steps:
   - uses: Slashgear/action-check-pr-title@v4.3.0
     with:
        regexp: "ACDEV*" # Regex the title should match.
