name: CI

on:
  push:
     branches:
     - "feature"


jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v2
    - name: Run a script
      run: echo "Running in DEV"
   
